### ISSUE TITLE
Define a name for the site

### ISSUE THREAD

**Issue by dcruzb** [trading-album-stickers/trading-album-stickers-front#10]
The site is for trading album stickers, specially for the FIFA World Cup Panini sticker album.

A site were users are able to register sticker that they need, or sticker that they have that others may need! 

We need to define a good name for the site, and the domain.

To be accept just PR the readme with a name suggestion.

**Comment by pratik9315** [comment]
i have a few suggestions before making a pr:

1. Sticker registry
2. Stickerbase
3. Sticker trader
4. Sticker collection

Let me know what do you think😄

**Comment by dcruzb** [comment]
Thanks for the contribution @pratik2315 !
I liked the names Sticker Trader and Sticker Collection better!

Since the main goal of the project is to help people complete the "collection" through "tradding" stickers I think they're the most appropriate.

Between these two I would take the "Sticker Collection".

Please make the PR and I will accept it!

**Comment by pratik9315** [comment]
hey @dcbCIn ! i have added the name sticker collection in the readme of the repo as you suggested. pls check it out and point out any mistake i may have done😄

**Comment by dcruzb** [comment]
@all-contributors please add @pratik2315 for docs
