### ISSUE TITLE
Create a logo for the site

### ISSUE THREAD

**Issue by dcruzb** [trading-album-stickers/trading-album-stickers-front#4]
I'm open to any suggestions, but I was thinking something like pasting a sticker, or maybe something that resembles the act of trading the sticker

At the [design folder](https://github.com/trading-album-stickers/trading-album-stickers-front/tree/main/design) you may find the color palette

**Comment by yuricdb** [comment]
@dcbCIn can you assign this to me, plz

**Comment by dcruzb** [comment]
Sure, thanks for the interest!
