### ISSUE TITLE
Enhance the readme for the project

### ISSUE THREAD

**Issue by dcruzb** [trading-album-stickers/trading-album-stickers-front#5]
You define the scope! The intention is to build a site to help people complete any sticker album that they have through trading or selling album stickers.
The readme should introduce users to what the site really is!

I see a site were users are able to register sticker that they need, or sticker that they have that others may need!

Feel free to improve as you want!

**Comment by imgourav** [comment]
Can I add the section for "Steps of Contribution to this repository" and some enhancements in the README file, if yes! 
Please assign this issue to me @dcbCIn , I can do this :)

**Comment by dcruzb** [comment]
Thanks for the contribution @imgourav!
