### ISSUE TITLE
Define color palette

### ISSUE THREAD

**Issue by dcruzb** [trading-album-stickers/trading-album-stickers-front#6]
We must define a color palette to start developing the prototype!

This is a site for trading album stickers, specially for the FIFA World Cup Panini sticker album.

Feel free to improve as you want!

**Comment by william-monroy** [comment]
Hi @dcbCIn , could you assign me this issue?

**Comment by dcruzb** [comment]
I've assigned this issue to you, thank you for the contribution!

**Comment by william-monroy** [comment]
Thanks, could you review my pull request #25  please?

**Comment by dcruzb** [comment]
Sure, I've added a simple change request there!

**Comment by dcruzb** [comment]
Thank you again for the contribution!
