### ISSUE TITLE
Create site icon

### ISSUE THREAD

**Issue by dcruzb** [trading-album-stickers/trading-album-stickers-front#7]
We must define a icon for the site!

This is a site for trading album stickers, specially for the FIFA World Cup Panini sticker album.

Feel free to improve as you want!

**Comment by komalsoni4** [comment]
please assign me this issue

**Comment by dcruzb** [comment]
Thank you for your interest in contributing to the project!

**Comment by SaxenaAnushka102** [comment]
Hello @dcbCIn! I'd like to contribute could you please assign this issue to me ?

**Comment by dcruzb** [comment]
Sure @SaxenaAnushka102 ! Even if @komalsoni4 submit a PR I will accept both, since the idea is contribute and enhance. Any suggestion is welcome too!

**Comment by SaxenaAnushka102** [comment]
Hey @dcbCIn , thanks for assigning. I'm on it! Could you please provide the required picture resolution & dimension details?

**Comment by sowmiyeh** [comment]
Hi @dcbCIn Could you please assign me this issue?

**Comment by dcruzb** [comment]
@SaxenaAnushka102 , please provide the image in raw format too.
The initial ideal was 
16x16
32x32
96x96
180x180

**Comment by dcruzb** [comment]
@sowmiya-venkatesan sure!

**Comment by SaxenaAnushka102** [comment]
Hello @dcbCIn! I've created a few designs. Can I share them on your mail to finalize?

**Comment by dcruzb** [comment]
@SaxenaAnushka102 please submit a PR and I will accept it! I've create another issue to receive the Pull Request. Issue #59. In case of doubts about how to do it, you can ask
